version: '3'
services:
  db:
    build: ./mysql
    container_name: api-database
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3310:3306'
    networks:
      - carApiNetwork
  api:
    container_name: car-api
    restart: on-failure
    build: ./car-api
    environment:
      - SPRINGPROFILES=prod
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - carApiNetwork
networks:
   carApiNetwork:
    external: true
    name: carApiNetwork
