version: '3'
services:
  db:
    build: ./mysql
    container_name: api-database
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3310:3306'
    networks:
      - carApiNetwork
  api:
    container_name: car-api
    build: ./car-api
    environment:
      - SPRINGPROFILES=prod
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - carApiNetwork
  frontend:
    container_name: api-frontend
    image: joseluisq/static-web-server:2
    environment:
      - SERVER_CORS_ALLOW_ORIGINS=*
      - SERVER_LOG_LEVEL=debug
      - SERVER_ROOT=/public
    volumes:
      -  ./frontend/files:/public
    ports:
      - 3124:80
    networks:
      - carApiNetwork
networks:
   carApiNetwork:
    external: true
    name: carApiNetwork
