-- CREATE TABLE test (
-- 	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
-- );
DROP TABLE IF EXISTS CAR CASCADE;
CREATE TABLE IF NOT EXISTS CAR (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	year INT NOT NULL,
	make VARCHAR(50) NULL,
	model VARCHAR(50) NOT NULL
    );