FROM openjdk:11
RUN echo "Europe/London" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
RUN mkdir /data
WORKDIR /data
ADD cars-0.0.1-SNAPSHOT.jar /data/myapp.jar

ENV SPRINGPROFILES="test"

ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar -Dspring.profiles.active="$SPRINGPROFILES" myapp.jar

#when "-XX:+UseCGroupMemoryLimitForHeap" isn't experimental anymore, you can use the following
#ENTRYPOINT java -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom -jar -Dspring.profiles.active="$springprofiles" myapp.jar

EXPOSE 8080